# Define the image for the run environment
image: docker:latest
services:
- docker:dind
    
# Name the stages involved in the pipeline
stages:
- build
- test
- deploy

maven-install:
  image: maven:3-jdk-8
  tags: shell
  stage: build
  script: 
    - cd ./code/server
    - mvn clean install
  artifacts: target/*.jar
  paths: target/*.jar

test:
    stage: test
    only:
        - master
    script:
        - echo run tests in this phase
