# Define the image for the run environment
image: node:latest
    
# Name the stages involved in the pipeline
stages:
- build-npm
- test-mvn
- install-mvn

cache:
  path:
    - node_modules/
    - ./code/client/node_modules/

install-npm-dependencies:
  stage: build-npm
  tags:
    - shell
  script:
    - cd ./code/client
    - npm install
  only:
    - master
  artifacts:
    paths:
      - node_modules/
  
maven-test:
  stage: test-mvn
  tags: 
    - shell
  script: 
    - cd ./code/server
    - mvn clean test
  only:
    - master
    
maven-install:
  stage: install-mvn
  tags:
    - shell
  script:
    - cd ./code/server
    - mvn install
  artifacts:
    paths:
      - target/*.jar
  only:
    - master
