image: node:latest

stages:
  - build
  - test
  
install-npm-dependencies:
  tags:
    - docker
  stage: build
  script:
    - echo "npm install script here"
  only:
    - master
    
maven-test:
  tags:
    - docker
  stage: test
  script:
  - echo "maven tests here"
  only:
    - master
  
  