image: node:latest

stages:
  - build
  - test
  
install-npm-dependencies:
  tags:
    only:
      - docker
  stage: build
  script:
    - echo "npm install script here"
    
maven-test:
  tags:
    only:
      - docker
  stage: test
  script:
  - echo "maven tests here"
  
  